version: "3.9"
services: 
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./ngnix
    ports:
      - "80:80"
    depends_on: 
      - api
      - client
  client:
    build: 
      dockerfile: Dockerfile
      context: ./game-front-end
    depends_on:
      - api
  api:
    build:
      dockerfile: Dockerfile
      context: ./back-end-python