version: "3.9"
services: 
  nginx:
    image: exfhow.azurecr.io/game_nginx
    ports:
      - "80:80"
    depends_on: 
      - api
      - client
  client:
    image: exfhow.azurecr.io/game_fe_vue
    depends_on:
      - api
  api:
    image: exfhow.azurecr.io/game_be_python
    ports:
      - "4000:4000"

